apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: my-app
    spec:
      serviceAccountName: my-app-service-account
      containers:
        - name: app-container
          image: my-app-image
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: my-db-secret-name
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-db-secret-name
                  key: password
