apiVersion: config.istio.io/v1alpha2
kind: QuotaSpec
metadata:
  name: global-quotaspec
  namespace: istio-system
spec:
  rules:
  - quotas:
    - charge: 1
      quota: requestcount
    - charge: 1000
      quota: requestcount.rpm
