apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: developer-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: v1
kind: List
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: developer-binding-namespace1
  subjects:
  - kind: User
    name: developer-username
    apiGroup: rbac.authorization.k8s.io
  roleRef:
    kind: ClusterRole
    name: developer-role
    apiGroup: rbac.authorization.k8s.io
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: developer-binding-namespace2
  subjects:
  - kind: User
    name: developer-username
    apiGroup: rbac.authorization.k8s.io
  roleRef:
    kind: ClusterRole
    name: developer-role
    apiGroup: rbac.authorization.k8s.io
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: developer-binding-namespace3
  subjects:
  - kind: User
    name: developer-username
    apiGroup: rbac.authorization.k8s.io
  roleRef:
    kind: ClusterRole
    name: developer-role
    apiGroup: rbac.authorization.k8s.io
# Repeat the ClusterRoleBinding section for each namespace
